name: OpenRSC

options:
  deploymentTarget:
    iOS: "16.0"

targets:
  OpenRSC:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - OpenRSC/Sources
    resources:
      - ../../server/bin/main/server/defs/ItemDefs.json
      - ../../Client_Base/Cache/video/Authentic_Sprites.orsc
      - ../../Client_Base/Cache/video/Authentic_Landscape.orsc
    settings:
      base:
        PRODUCT_NAME: OpenRSC
        PRODUCT_BUNDLE_IDENTIFIER: com.openrsc.ios
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIStatusBarHidden: YES
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: MJAYYU2WWD
        CODE_SIGN_IDENTITY: iPhone Developer
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"

schemes:
  OpenRSC:
    build:
      targets:
        OpenRSC: all
