// Auto-generated from server/conf/server/defs/ItemDefs.json
// Item type ID → display name

enum ItemNames {
    static func name(for id: Int) -> String {
        guard id >= 0, id < itemNames.count else { return "Item \(id)" }
        return itemNames[id]
    }

    // 1290 item definitions
    static let itemNames: [String] = [
        "Iron Mace",
        "Iron Short Sword",
        "Iron Kite Shield",
        "Iron Square Shield",
        "Wooden Shield",
        "Medium Iron Helmet",
        "Large Iron Helmet",
        "Iron Chain Mail Body",
        "Iron Plate Mail Body",
        "Iron Plate Mail Legs",
        "Coins",
        "Bronze Arrows",
        "Iron Axe",
        "Knife",
        "Logs",
        "Leather Armour",
        "Leather Gloves",
        "Boots",
        "Cabbage",
        "Egg",
        "Bones",
        "Bucket",
        "Milk",
        "Flour",
        "Amulet of GhostSpeak",
        "Silverlight key 1",
        "Silverlight key 2",
        "skull",
        "Iron dagger",
        "grain",
        "Book",
        "Fire-Rune",
        "Water-Rune",
        "Air-Rune",
        "Earth-Rune",
        "Mind-Rune",
        "Body-Rune",
        "Life-Rune",
        "Death-Rune",
        "Needle",
        "Nature-Rune",
        "Chaos-Rune",
        "Law-Rune",
        "Thread",
        "Holy Symbol of saradomin",
        "Unblessed Holy Symbol",
        "Cosmic-Rune",
        "key",
        "key",
        "scroll",
        "Water",
        "Silverlight key 3",
        "Silverlight",
        "Broken shield",
        "Broken shield",
        "Cadavaberries",
        "message",
        "Cadava",
        "potion",
        "Phoenix Crossbow",
        "Crossbow",
        "Certificate",
        "bronze dagger",
        "Steel dagger",
        "Mithril dagger",
        "Adamantite dagger",
        "Bronze Short Sword",
        "Steel Short Sword",
        "Mithril Short Sword",
        "Adamantite Short Sword",
        "Bronze Long Sword",
        "Iron Long Sword",
        "Steel Long Sword",
        "Mithril Long Sword",
        "Adamantite Long Sword",
        "Rune long sword",
        "Bronze 2-handed Sword",
        "Iron 2-handed Sword",
        "Steel 2-handed Sword",
        "Mithril 2-handed Sword",
        "Adamantite 2-handed Sword",
        "rune 2-handed Sword",
        "Bronze Scimitar",
        "Iron Scimitar",
        "Steel Scimitar",
        "Mithril Scimitar",
        "Adamantite Scimitar",
        "bronze Axe",
        "Steel Axe",
        "Iron battle Axe",
        "Steel battle Axe",
        "Mithril battle Axe",
        "Adamantite battle Axe",
        "Rune battle Axe",
        "Bronze Mace",
        "Steel Mace",
        "Mithril Mace",
        "Adamantite Mace",
        "Rune Mace",
        "Brass key",
        "staff",
        "Staff of Air",
        "Staff of water",
        "Staff of earth",
        "Medium Bronze Helmet",
        "Medium Steel Helmet",
        "Medium Mithril Helmet",
        "Medium Adamantite Helmet",
        "Large Bronze Helmet",
        "Large Steel Helmet",
        "Large Mithril Helmet",
        "Large Adamantite Helmet",
        "Large Rune Helmet",
        "Bronze Chain Mail Body",
        "Steel Chain Mail Body",
        "Mithril Chain Mail Body",
        "Adamantite Chain Mail Body",
        "Bronze Plate Mail Body",
        "Steel Plate Mail Body",
        "Mithril Plate Mail Body",
        "Adamantite Plate Mail Body",
        "Steel Plate Mail Legs",
        "Mithril Plate Mail Legs",
        "Adamantite Plate Mail Legs",
        "Bronze Square Shield",
        "Steel Square Shield",
        "Mithril Square Shield",
        "Adamantite Square Shield",
        "Bronze Kite Shield",
        "Steel Kite Shield",
        "Mithril Kite Shield",
        "Adamantite Kite Shield",
        "cookedmeat",
        "raw chicken",
        "burntmeat",
        "pot",
        "flour",
        "bread dough",
        "bread",
        "burntbread",
        "jug",
        "water",
        "wine",
        "grapes",
        "shears",
        "wool",
        "fur",
        "cow hide",
        "leather",
        "clay",
        "copper ore",
        "iron ore",
        "gold",
        "mithril ore",
        "adamantite ore",
        "coal",
        "Bronze Pickaxe",
        "uncut diamond",
        "uncut ruby",
        "uncut emerald",
        "uncut sapphire",
        "diamond",
        "ruby",
        "emerald",
        "sapphire",
        "Herb",
        "tinderbox",
        "chisel",
        "hammer",
        "bronze bar",
        "iron bar",
        "steel bar",
        "gold bar",
        "mithril bar",
        "adamantite bar",
        "Pressure gauge",
        "Fish Food",
        "Poison",
        "Poisoned fish food",
        "spinach roll",
        "Bad wine",
        "Ashes",
        "Apron",
        "Cape",
        "Wizards robe",
        "wizardshat",
        "Brass necklace",
        "skirt",
        "Longbow",
        "Shortbow",
        "Crossbow bolts",
        "Apron",
        "Chef's hat",
        "Beer",
        "skirt",
        "skirt",
        "Black Plate Mail Body",
        "Staff of fire",
        "Magic Staff",
        "wizardshat",
        "silk",
        "flier",
        "tin ore",
        "Mithril Axe",
        "Adamantite Axe",
        "bronze battle Axe",
        "Bronze Plate Mail Legs",
        "Ball of wool",
        "Oil can",
        "Cape",
        "Kebab",
        "Spade",
        "Closet Key",
        "rubber tube",
        "Bronze Plated Skirt",
        "Iron Plated Skirt",
        "Black robe",
        "stake",
        "Garlic",
        "Red spiders eggs",
        "Limpwurt root",
        "Strength Potion",
        "Strength Potion",
        "Strength Potion",
        "Strength Potion",
        "Steel Plated skirt",
        "Mithril Plated skirt",
        "Adamantite Plated skirt",
        "Cabbage",
        "Cape",
        "Large Black Helmet",
        "Red Bead",
        "Yellow Bead",
        "Black Bead",
        "White Bead",
        "Amulet of accuracy",
        "Redberries",
        "Rope",
        "Reddye",
        "Yellowdye",
        "Paste",
        "Onion",
        "Bronze key",
        "Soft Clay",
        "wig",
        "wig",
        "Half full wine jug",
        "Keyprint",
        "Black Plate Mail Legs",
        "banana",
        "pastry dough",
        "Pie dish",
        "cooking apple",
        "pie shell",
        "Uncooked apple pie",
        "Uncooked meat pie",
        "Uncooked redberry pie",
        "apple pie",
        "Redberry pie",
        "meat pie",
        "burntpie",
        "Half a meat pie",
        "Half a Redberry pie",
        "Half an apple pie",
        "Portrait",
        "Faladian Knight's sword",
        "blurite ore",
        "Asgarnian Ale",
        "Wizard's Mind Bomb",
        "Dwarven Stout",
        "Eye of newt",
        "Rat's tail",
        "Bluedye",
        "Goblin Armour",
        "Goblin Armour",
        "Goblin Armour",
        "unstrung Longbow",
        "unstrung shortbow",
        "Unfired Pie dish",
        "unfired pot",
        "arrow shafts",
        "Woad Leaf",
        "Orangedye",
        "Gold ring",
        "Sapphire ring",
        "Emerald ring",
        "Ruby ring",
        "Diamond ring",
        "Gold necklace",
        "Sapphire necklace",
        "Emerald necklace",
        "Ruby necklace",
        "Diamond necklace",
        "ring mould",
        "Amulet mould",
        "Necklace mould",
        "Gold Amulet",
        "Sapphire Amulet",
        "Emerald Amulet",
        "Ruby Amulet",
        "Diamond Amulet",
        "Gold Amulet",
        "Sapphire Amulet",
        "Emerald Amulet",
        "Ruby Amulet",
        "Diamond Amulet",
        "superchisel",
        "Mace of Zamorak",
        "Bronze Plate Mail top",
        "Steel Plate Mail top",
        "Mithril Plate Mail top",
        "Adamantite Plate Mail top",
        "Iron Plate Mail top",
        "Black Plate Mail top",
        "Sapphire Amulet of magic",
        "Emerald Amulet of protection",
        "Ruby Amulet of strength",
        "Diamond Amulet of power",
        "Karamja Rum",
        "Cheese",
        "Tomato",
        "Pizza Base",
        "Burnt Pizza",
        "Incomplete Pizza",
        "Uncooked Pizza",
        "Plain Pizza",
        "Meat Pizza",
        "Anchovie Pizza",
        "Half Meat Pizza",
        "Half Anchovie Pizza",
        "Cake",
        "Burnt Cake",
        "Chocolate Cake",
        "Partial Cake",
        "Partial Chocolate Cake",
        "Slice of Cake",
        "Chocolate Slice",
        "Chocolate Bar",
        "Cake Tin",
        "Uncooked cake",
        "Unfired bowl",
        "Bowl",
        "Bowl of water",
        "Incomplete stew",
        "Incomplete stew",
        "Uncooked stew",
        "Stew",
        "Burnt Stew",
        "Potato",
        "Raw Shrimp",
        "Shrimp",
        "Raw Anchovies",
        "Anchovies",
        "Burnt fish",
        "Raw Sardine",
        "Sardine",
        "Raw Salmon",
        "Salmon",
        "Raw Trout",
        "Trout",
        "Burnt fish",
        "Raw Herring",
        "Herring",
        "Raw Pike",
        "Pike",
        "Burnt fish",
        "Raw Tuna",
        "Tuna",
        "Burnt fish",
        "Raw Swordfish",
        "Swordfish",
        "Burnt Swordfish",
        "Raw Lobster",
        "Lobster",
        "Burnt Lobster",
        "Lobster Pot",
        "Net",
        "Fishing Rod",
        "Fly Fishing Rod",
        "Harpoon",
        "Fishing Bait",
        "Feather",
        "Chest key",
        "Silver",
        "silver bar",
        "Holy Symbol of saradomin",
        "Holy symbol mould",
        "Disk of Returning",
        "Monks robe",
        "Monks robe",
        "Red key",
        "Orange Key",
        "yellow key",
        "Blue key",
        "Magenta key",
        "black key",
        "rune dagger",
        "Rune short sword",
        "rune Scimitar",
        "Medium Rune Helmet",
        "Rune Chain Mail Body",
        "Rune Plate Mail Body",
        "Rune Plate Mail Legs",
        "Rune Square Shield",
        "Rune Kite Shield",
        "rune Axe",
        "Rune skirt",
        "Rune Plate Mail top",
        "Runite bar",
        "runite ore",
        "Plank",
        "Tile",
        "skull",
        "Big Bones",
        "Muddy key",
        "Map",
        "Map Piece",
        "Map Piece",
        "Map Piece",
        "Nails",
        "Anti dragon breath Shield",
        "Maze key",
        "Pumpkin",
        "Black dagger",
        "Black Short Sword",
        "Black Long Sword",
        "Black 2-handed Sword",
        "Black Scimitar",
        "Black Axe",
        "Black battle Axe",
        "Black Mace",
        "Black Chain Mail Body",
        "Black Square Shield",
        "Black Kite Shield",
        "Black Plated skirt",
        "Herb",
        "Herb",
        "Herb",
        "Herb",
        "Herb",
        "Herb",
        "Herb",
        "Herb",
        "Herb",
        "Guam leaf",
        "Marrentill",
        "Tarromin",
        "Harralander",
        "Ranarr Weed",
        "Irit Leaf",
        "Avantoe",
        "Kwuarm",
        "Cadantine",
        "Dwarf Weed",
        "Unfinished potion",
        "Unfinished potion",
        "Unfinished potion",
        "Unfinished potion",
        "Unfinished potion",
        "Unfinished potion",
        "Unfinished potion",
        "Unfinished potion",
        "Unfinished potion",
        "Unfinished potion",
        "Vial",
        "Vial",
        "Unicorn horn",
        "Blue dragon scale",
        "Pestle and mortar",
        "Snape grass",
        "Medium black Helmet",
        "White berries",
        "Ground blue dragon scale",
        "Ground unicorn horn",
        "attack Potion",
        "attack Potion",
        "attack Potion",
        "stat restoration Potion",
        "stat restoration Potion",
        "stat restoration Potion",
        "defense Potion",
        "defense Potion",
        "defense Potion",
        "restore prayer Potion",
        "restore prayer Potion",
        "restore prayer Potion",
        "Super attack Potion",
        "Super attack Potion",
        "Super attack Potion",
        "fishing Potion",
        "fishing Potion",
        "fishing Potion",
        "Super strength Potion",
        "Super strength Potion",
        "Super strength Potion",
        "Super defense Potion",
        "Super defense Potion",
        "Super defense Potion",
        "ranging Potion",
        "ranging Potion",
        "ranging Potion",
        "wine of Zamorak",
        "raw bear meat",
        "raw rat meat",
        "raw beef",
        "enchanted bear meat",
        "enchanted rat meat",
        "enchanted beef",
        "enchanted chicken meat",
        "Dramen Staff",
        "Dramen Branch",
        "Cape",
        "Cape",
        "Cape",
        "Cape",
        "Greendye",
        "Purpledye",
        "Iron ore certificate",
        "Coal certificate",
        "Mithril ore certificate",
        "silver certificate",
        "Gold certificate",
        "Dragonstone Amulet",
        "Dragonstone",
        "Dragonstone Amulet",
        "Crystal key",
        "Half of a key",
        "Half of a key",
        "Iron bar certificate",
        "steel bar certificate",
        "Mithril bar certificate",
        "silver bar certificate",
        "Gold bar certificate",
        "Lobster certificate",
        "Raw lobster certificate",
        "Swordfish certificate",
        "Raw swordfish certificate",
        "Diary",
        "Front door key",
        "Ball",
        "magnet",
        "Grey wolf fur",
        "uncut dragonstone",
        "Dragonstone ring",
        "Dragonstone necklace",
        "Raw Shark",
        "Shark",
        "Burnt Shark",
        "Big Net",
        "Casket",
        "Raw cod",
        "Cod",
        "Raw Mackerel",
        "Mackerel",
        "Raw Bass",
        "Bass",
        "Ice Gloves",
        "Firebird Feather",
        "Firebird Feather",
        "Poisoned Iron dagger",
        "Poisoned bronze dagger",
        "Poisoned Steel dagger",
        "Poisoned Mithril dagger",
        "Poisoned Rune dagger",
        "Poisoned Adamantite dagger",
        "Poisoned Black dagger",
        "Cure poison Potion",
        "Cure poison Potion",
        "Cure poison Potion",
        "Poison antidote",
        "Poison antidote",
        "Poison antidote",
        "weapon poison",
        "ID Paper",
        "Poison Bronze Arrows",
        "Christmas cracker",
        "Party Hat",
        "Party Hat",
        "Party Hat",
        "Party Hat",
        "Party Hat",
        "Party Hat",
        "Miscellaneous key",
        "Bunch of keys",
        "Whisky",
        "Candlestick",
        "Master thief armband",
        "Blamish snail slime",
        "Blamish oil",
        "Oily Fishing Rod",
        "lava eel",
        "Raw lava eel",
        "Poison Crossbow bolts",
        "Dragon sword",
        "Dragon axe",
        "Jail keys",
        "Dusty Key",
        "Charged Dragonstone Amulet",
        "Grog",
        "Candle",
        "black Candle",
        "Candle",
        "black Candle",
        "insect repellant",
        "Bat bones",
        "wax Bucket",
        "Excalibur",
        "Druids robe",
        "Druids robe",
        "Eye patch",
        "Unenchanted Dragonstone Amulet",
        "Unpowered orb",
        "Fire orb",
        "Water orb",
        "Battlestaff",
        "Battlestaff of fire",
        "Battlestaff of water",
        "Battlestaff of air",
        "Battlestaff of earth",
        "Blood-Rune",
        "Beer glass",
        "glassblowing pipe",
        "seaweed",
        "molten glass",
        "soda ash",
        "sand",
        "air orb",
        "earth orb",
        "bass certificate",
        "Raw bass certificate",
        "shark certificate",
        "Raw shark certificate",
        "Oak Logs",
        "Willow Logs",
        "Maple Logs",
        "Yew Logs",
        "Magic Logs",
        "Headless Arrows",
        "Iron Arrows",
        "Poison Iron Arrows",
        "Steel Arrows",
        "Poison Steel Arrows",
        "Mithril Arrows",
        "Poison Mithril Arrows",
        "Adamantite Arrows",
        "Poison Adamantite Arrows",
        "Rune Arrows",
        "Poison Rune Arrows",
        "Oak Longbow",
        "Oak Shortbow",
        "Willow Longbow",
        "Willow Shortbow",
        "Maple Longbow",
        "Maple Shortbow",
        "Yew Longbow",
        "Yew Shortbow",
        "Magic Longbow",
        "Magic Shortbow",
        "unstrung Oak Longbow",
        "unstrung Oak Shortbow",
        "unstrung Willow Longbow",
        "unstrung Willow Shortbow",
        "unstrung Maple Longbow",
        "unstrung Maple Shortbow",
        "unstrung Yew Longbow",
        "unstrung Yew Shortbow",
        "unstrung Magic Longbow",
        "unstrung Magic Shortbow",
        "barcrawl card",
        "bronze arrow heads",
        "iron arrow heads",
        "steel arrow heads",
        "mithril arrow heads",
        "adamantite arrow heads",
        "rune arrow heads",
        "flax",
        "bow string",
        "Easter egg",
        "scorpion cage",
        "scorpion cage",
        "scorpion cage",
        "scorpion cage",
        "Enchanted Battlestaff of fire",
        "Enchanted Battlestaff of water",
        "Enchanted Battlestaff of air",
        "Enchanted Battlestaff of earth",
        "scorpion cage",
        "scorpion cage",
        "scorpion cage",
        "scorpion cage",
        "gold",
        "gold bar",
        "Ruby ring",
        "Ruby necklace",
        "Family crest",
        "Crest fragment",
        "Crest fragment",
        "Crest fragment",
        "Steel gauntlets",
        "gauntlets of goldsmithing",
        "gauntlets of cooking",
        "gauntlets of chaos",
        "robe of Zamorak",
        "robe of Zamorak",
        "Address Label",
        "Tribal totem",
        "tourist guide",
        "spice",
        "Uncooked curry",
        "curry",
        "Burnt curry",
        "yew logs certificate",
        "maple logs certificate",
        "willow logs certificate",
        "lockpick",
        "Red vine worms",
        "Blanket",
        "Raw giant carp",
        "giant Carp",
        "Fishing competition Pass",
        "Hemenster fishing trophy",
        "Pendant of Lucien",
        "Boots of lightfootedness",
        "Ice Arrows",
        "Lever",
        "Staff of Armadyl",
        "Pendant of Armadyl",
        "Large cog",
        "Large cog",
        "Large cog",
        "Large cog",
        "Rat Poison",
        "shiny Key",
        "khazard Helmet",
        "khazard chainmail",
        "khali brew",
        "khazard cell keys",
        "Poison chalice",
        "magic whistle",
        "Cup of tea",
        "orb of protection",
        "orbs of protection",
        "Holy table napkin",
        "bell",
        "Gnome Emerald Amulet of protection",
        "magic golden feather",
        "Holy grail",
        "Script of Hazeel",
        "Pineapple",
        "Pineapple ring",
        "Pineapple Pizza",
        "Half pineapple Pizza",
        "Magic scroll",
        "Mark of Hazeel",
        "bloody axe of zamorak",
        "carnillean armour",
        "Carnillean Key",
        "Cattle prod",
        "Plagued sheep remains",
        "Poisoned animal feed",
        "Protective jacket",
        "Protective trousers",
        "Plagued sheep remains",
        "Plagued sheep remains",
        "Plagued sheep remains",
        "dwellberries",
        "Gasmask",
        "picture",
        "Book",
        "Seaslug",
        "chocolaty milk",
        "Hangover cure",
        "Chocolate dust",
        "Torch",
        "Torch",
        "warrant",
        "Damp sticks",
        "Dry sticks",
        "Broken glass",
        "oyster pearls",
        "little key",
        "Scruffy note",
        "Glarial's amulet",
        "Swamp tar",
        "Uncooked Swamp paste",
        "Swamp paste",
        "Oyster pearl bolts",
        "Glarials pebble",
        "book on baxtorian",
        "large key",
        "Oyster pearl bolt tips",
        "oyster",
        "oyster pearls",
        "oyster",
        "Soil",
        "Dragon medium Helmet",
        "Mithril seed",
        "An old key",
        "pigeon cage",
        "Messenger pigeons",
        "Bird feed",
        "Rotten apples",
        "Doctors gown",
        "Bronze key",
        "Distillator",
        "Glarial's urn",
        "Glarial's urn",
        "Priest robe",
        "Priest gown",
        "Liquid Honey",
        "Ethenea",
        "Sulphuric Broline",
        "Plague sample",
        "Touch paper",
        "Dragon Bones",
        "Herb",
        "Snake Weed",
        "Herb",
        "Ardrigal",
        "Herb",
        "Sito Foil",
        "Herb",
        "Volencia Moss",
        "Herb",
        "Rogues Purse",
        "Soul-Rune",
        "king lathas Amulet",
        "Bronze Spear",
        "halloween mask",
        "Dragon bitter",
        "Greenmans ale",
        "halloween mask",
        "halloween mask",
        "cocktail glass",
        "cocktail shaker",
        "Bone Key",
        "gnome robe",
        "gnome robe",
        "gnome robe",
        "gnome robe",
        "gnome robe",
        "gnomeshat",
        "gnomeshat",
        "gnomeshat",
        "gnomeshat",
        "gnomeshat",
        "gnome top",
        "gnome top",
        "gnome top",
        "gnome top",
        "gnome top",
        "gnome cocktail guide",
        "Beads of the dead",
        "cocktail glass",
        "cocktail glass",
        "lemon",
        "lemon slices",
        "orange",
        "orange slices",
        "Diced orange",
        "Diced lemon",
        "Fresh Pineapple",
        "Pineapple chunks",
        "lime",
        "lime chunks",
        "lime slices",
        "fruit blast",
        "odd looking cocktail",
        "Whisky",
        "vodka",
        "gin",
        "cream",
        "Drunk dragon",
        "Equa leaves",
        "SGG",
        "Chocolate saturday",
        "brandy",
        "blurberry special",
        "wizard blizzard",
        "pineapple punch",
        "gnomebatta dough",
        "gianne dough",
        "gnomebowl dough",
        "gnomecrunchie dough",
        "gnomebatta",
        "gnomebowl",
        "gnomebatta",
        "gnomecrunchie",
        "gnomebowl",
        "Uncut Red Topaz",
        "Uncut Jade",
        "Uncut Opal",
        "Red Topaz",
        "Jade",
        "Opal",
        "Swamp Toad",
        "Toad legs",
        "King worm",
        "Gnome spice",
        "gianne cook book",
        "gnomecrunchie",
        "cheese and tomato batta",
        "toad batta",
        "gnome batta",
        "worm batta",
        "fruit batta",
        "Veg batta",
        "Chocolate bomb",
        "Vegball",
        "worm hole",
        "Tangled toads legs",
        "Choc crunchies",
        "Worm crunchies",
        "Toad crunchies",
        "Spice crunchies",
        "Crushed Gemstone",
        "Blurberry badge",
        "Gianne badge",
        "tree gnome translation",
        "Bark sample",
        "War ship",
        "gloughs journal",
        "invoice",
        "Ugthanki Kebab",
        "special curry",
        "glough's key",
        "glough's notes",
        "Pebble",
        "Pebble",
        "Pebble",
        "Pebble",
        "Daconia rock",
        "Sinister key",
        "Herb",
        "Torstol",
        "Unfinished potion",
        "Jangerberries",
        "fruit blast",
        "blurberry special",
        "wizard blizzard",
        "pineapple punch",
        "SGG",
        "Chocolate saturday",
        "Drunk dragon",
        "cheese and tomato batta",
        "toad batta",
        "gnome batta",
        "worm batta",
        "fruit batta",
        "Veg batta",
        "Chocolate bomb",
        "Vegball",
        "worm hole",
        "Tangled toads legs",
        "Choc crunchies",
        "Worm crunchies",
        "Toad crunchies",
        "Spice crunchies",
        "Stone-Plaque",
        "Tattered Scroll",
        "Crumpled Scroll",
        "Bervirius Tomb Notes",
        "Zadimus Corpse",
        "Potion of Zamorak",
        "Potion of Zamorak",
        "Potion of Zamorak",
        "Boots",
        "Boots",
        "Boots",
        "Boots",
        "Boots",
        "Santa's hat",
        "Locating Crystal",
        "Sword Pommel",
        "Bone Shard",
        "Steel Wire",
        "Bone Beads",
        "Rashiliya Corpse",
        "ResetCrystal",
        "Bronze Wire",
        "Present",
        "Gnome Ball",
        "Papyrus",
        "A lump of Charcoal",
        "Arrow",
        "Lit Arrow",
        "Rocks",
        "Paramaya Rest Ticket",
        "Ship Ticket",
        "Damp cloth",
        "Desert Boots",
        "Orb of light",
        "Orb of light",
        "Orb of light",
        "Orb of light",
        "Railing",
        "Randas's journal",
        "Unicorn horn",
        "Coat of Arms",
        "Coat of Arms",
        "Staff of Iban",
        "Dwarf brew",
        "Ibans Ashes",
        "Cat",
        "A Doll of Iban",
        "Old Journal",
        "Klank's gauntlets",
        "Iban's shadow",
        "Iban's conscience",
        "Amulet of Othainian",
        "Amulet of Doomion",
        "Amulet of Holthion",
        "keep key",
        "Bronze Throwing Dart",
        "Prototype Throwing Dart",
        "Iron Throwing Dart",
        "Full Water Skin",
        "Lens mould",
        "Lens",
        "Desert Robe",
        "Desert Shirt",
        "Metal Key",
        "Slaves Robe Bottom",
        "Slaves Robe Top",
        "Steel Throwing Dart",
        "Astrology Book",
        "Unholy Symbol mould",
        "Unholy Symbol of Zamorak",
        "Unblessed Unholy Symbol of Zamorak",
        "Unholy Symbol of Zamorak",
        "Shantay Desert Pass",
        "Staff of Iban",
        "Dwarf cannon base",
        "Dwarf cannon stand",
        "Dwarf cannon barrels",
        "Dwarf cannon furnace",
        "Fingernails",
        "Powering crystal1",
        "Mining Barrel",
        "Ana in a Barrel",
        "Stolen gold",
        "multi cannon ball",
        "Railing",
        "Ogre tooth",
        "Ogre relic",
        "Skavid map",
        "dwarf remains",
        "Key",
        "Ogre relic part",
        "Ogre relic part",
        "Ogre relic part",
        "Ground bat bones",
        "Unfinished potion",
        "Ogre potion",
        "Magic ogre potion",
        "Tool kit",
        "Nulodion's notes",
        "cannon ammo mould",
        "Tenti Pineapple",
        "Bedobin Copy Key",
        "Technical Plans",
        "Rock cake",
        "Bronze dart tips",
        "Iron dart tips",
        "Steel dart tips",
        "Mithril dart tips",
        "Adamantite dart tips",
        "Rune dart tips",
        "Mithril Throwing Dart",
        "Adamantite Throwing Dart",
        "Rune Throwing Dart",
        "Prototype dart tip",
        "info document",
        "Instruction manual",
        "Unfinished potion",
        "Iron throwing knife",
        "Bronze throwing knife",
        "Steel throwing knife",
        "Mithril throwing knife",
        "Adamantite throwing knife",
        "Rune throwing knife",
        "Black throwing knife",
        "Water Skin mostly full",
        "Water Skin mostly empty",
        "Water Skin mouthful left",
        "Empty Water Skin",
        "nightshade",
        "Shaman robe",
        "Iron Spear",
        "Steel Spear",
        "Mithril Spear",
        "Adamantite Spear",
        "Rune Spear",
        "Cat",
        "Seasoned Sardine",
        "Kittens",
        "Kitten",
        "Wrought iron key",
        "Cell Door Key",
        "A free Shantay Disclaimer",
        "Doogle leaves",
        "Raw Ugthanki Meat",
        "Tasty Ugthanki Kebab",
        "Cooked Ugthanki Meat",
        "Uncooked Pitta Bread",
        "Pitta Bread",
        "Tomato Mixture",
        "Onion Mixture",
        "Onion and Tomato Mixture",
        "Onion and Tomato and Ugthanki Mix",
        "Burnt Pitta Bread",
        "Panning tray",
        "Panning tray",
        "Panning tray",
        "Rock pick",
        "Specimen brush",
        "Specimen jar",
        "Rock Sample",
        "gold Nuggets",
        "cat",
        "Scrumpled piece of paper",
        "Digsite info",
        "Poisoned Bronze Throwing Dart",
        "Poisoned Iron Throwing Dart",
        "Poisoned Steel Throwing Dart",
        "Poisoned Mithril Throwing Dart",
        "Poisoned Adamantite Throwing Dart",
        "Poisoned Rune Throwing Dart",
        "Poisoned Bronze throwing knife",
        "Poisoned Iron throwing knife",
        "Poisoned Steel throwing knife",
        "Poisoned Mithril throwing knife",
        "Poisoned Black throwing knife",
        "Poisoned Adamantite throwing knife",
        "Poisoned Rune throwing knife",
        "Poisoned Bronze Spear",
        "Poisoned Iron Spear",
        "Poisoned Steel Spear",
        "Poisoned Mithril Spear",
        "Poisoned Adamantite Spear",
        "Poisoned Rune Spear",
        "Book of experimental chemistry",
        "Level 1 Certificate",
        "Level 2 Certificate",
        "Level 3 Certificate",
        "Trowel",
        "Stamped letter of recommendation",
        "Unstamped letter of recommendation",
        "Rock Sample",
        "Rock Sample",
        "Cracked rock Sample",
        "Belt buckle",
        "Powering crystal2",
        "Powering crystal3",
        "Powering crystal4",
        "Old boot",
        "Bunny ears",
        "Damaged armour",
        "Damaged armour",
        "Rusty sword",
        "Ammonium Nitrate",
        "Nitroglycerin",
        "Old tooth",
        "Radimus Scrolls",
        "chest key",
        "broken arrow",
        "buttons",
        "broken staff",
        "vase",
        "ceramic remains",
        "Broken glass",
        "Unidentified powder",
        "Machette",
        "Scroll",
        "stone tablet",
        "Talisman of Zaros",
        "Explosive compound",
        "Bull Roarer",
        "Mixed chemicals",
        "Ground charcoal",
        "Mixed chemicals",
        "Spell scroll",
        "Yommi tree seed",
        "Totem Pole",
        "Dwarf cannon base",
        "Dwarf cannon stand",
        "Dwarf cannon barrels",
        "Dwarf cannon furnace",
        "Golden Bowl",
        "Golden Bowl with pure water",
        "Raw Manta ray",
        "Manta ray",
        "Raw Sea turtle",
        "Sea turtle",
        "Annas Silver Necklace",
        "Bobs Silver Teacup",
        "Carols Silver Bottle",
        "Davids Silver Book",
        "Elizabeths Silver Needle",
        "Franks Silver Pot",
        "Thread",
        "Thread",
        "Thread",
        "Flypaper",
        "Murder Scene Pot",
        "A Silver Dagger",
        "Murderers fingerprint",
        "Annas fingerprint",
        "Bobs fingerprint",
        "Carols fingerprint",
        "Davids fingerprint",
        "Elizabeths fingerprint",
        "Franks fingerprint",
        "Zamorak Cape",
        "Saradomin Cape",
        "Guthix Cape",
        "Staff of zamorak",
        "Staff of guthix",
        "Staff of Saradomin",
        "A chunk of crystal",
        "A lump of crystal",
        "A hunk of crystal",
        "A red crystal",
        "Unidentified fingerprint",
        "Annas Silver Necklace",
        "Bobs Silver Teacup",
        "Carols Silver Bottle",
        "Davids Silver Book",
        "Elizabeths Silver Needle",
        "Franks Silver Pot",
        "A Silver Dagger",
        "A glowing red crystal",
        "Unidentified liquid",
        "Radimus Scrolls",
        "Robe",
        "Armour",
        "Dagger",
        "eye patch",
        "Booking of Binding",
        "Holy Water Vial",
        "Enchanted Vial",
        "Scribbled notes",
        "Scrawled notes",
        "Scatched notes",
        "Shamans Tome",
        "Edible seaweed",
        "Rough Sketch of a bowl",
        "Burnt Manta ray",
        "Burnt Sea turtle",
        "Cut reed plant",
        "Magical Fire Pass",
        "Snakes Weed Solution",
        "Ardrigal Solution",
        "Gujuo Potion",
        "Germinated Yommi tree seed",
        "Dark Dagger",
        "Glowing Dark Dagger",
        "Holy Force Spell",
        "Iron Pickaxe",
        "Steel Pickaxe",
        "Mithril Pickaxe",
        "Adamantite Pickaxe",
        "Rune Pickaxe",
        "Sleeping Bag",
        "A blue wizards hat",
        "Gilded Totem Pole",
        "Blessed Golden Bowl",
        "Blessed Golden Bowl with Pure Water",
        "Raw Oomlie Meat",
        "Cooked Oomlie meat Parcel",
        "Dragon Bone Certificate",
        "Limpwurt Root Certificate",
        "Prayer Potion Certificate",
        "Super Attack Potion Certificate",
        "Super Defense Potion Certificate",
        "Super Strength Potion Certificate",
        "Half Dragon Square Shield",
        "Half Dragon Square Shield",
        "Dragon Square Shield",
        "Palm tree leaf",
        "Raw Oomlie Meat Parcel",
        "Burnt Oomlie Meat parcel",
        "Bailing Bucket",
        "Plank",
        "Arcenia root",
        "display tea",
        "Blessed Golden Bowl with plain water",
        "Golden Bowl with plain water",
        "Cape of legends",
        "Scythe"
    ]
}
