// Auto-generated from server/conf/server/defs/NpcDefs.json
// NPC type ID → display name

enum NPCNames {
    static func name(for id: Int) -> String {
        guard id >= 0, id < npcNames.count else { return "NPC \(id)" }
        return npcNames[id]
    }

    // 794 NPC definitions from server/conf/server/defs/NpcDefs.json
    static let npcNames: [String] = [
        "Unicorn",
        "Bob",
        "Sheep",
        "Chicken",
        "Goblin",
        "Hans",
        "cow",
        "cook",
        "Bear",
        "Priest",
        "Urhney",
        "Man",
        "Bartender",
        "Camel",
        "Gypsy",
        "Ghost",
        "Sir Prysin",
        "Traiborn the wizard",
        "Captain Rovin",
        "Rat",
        "Reldo",
        "mugger",
        "Lesser Demon",
        "Giant Spider",
        "Man",
        "Jonny the beard",
        "Baraek",
        "Katrine",
        "Tramp",
        "Rat",
        "Romeo",
        "Juliet",
        "Father Lawrence",
        "Apothecary",
        "spider",
        "Delrith",
        "Veronica",
        "Weaponsmaster",
        "Professor Oddenstein",
        "Curator",
        "skeleton",
        "zombie",
        "king",
        "Giant bat",
        "Bartender",
        "skeleton",
        "skeleton",
        "Rat",
        "Horvik the Armourer",
        "Bear",
        "skeleton",
        "Shopkeeper",
        "zombie",
        "Ghost",
        "Aubury",
        "Shopkeeper",
        "shopkeeper",
        "Darkwizard",
        "lowe",
        "Thessalia",
        "Darkwizard",
        "Giant",
        "Goblin",
        "farmer",
        "Thief",
        "Guard",
        "Black Knight",
        "Hobgoblin",
        "zombie",
        "Zaff",
        "Scorpion",
        "silk trader",
        "Man",
        "Guide",
        "Giant Spider",
        "Peksa",
        "Barbarian",
        "Fred the farmer",
        "Gunthor the Brave",
        "Witch",
        "Ghost",
        "Wizard",
        "Shop Assistant",
        "Shop Assistant",
        "Zeke",
        "Louie Legs",
        "Warrior",
        "Shopkeeper",
        "Shop Assistant",
        "Highwayman",
        "Kebab Seller",
        "Chicken",
        "Ernest",
        "Monk",
        "Dwarf",
        "Banker",
        "Count Draynor",
        "Morgan",
        "Dr Harlow",
        "Deadly Red spider",
        "Guard",
        "Cassie",
        "White Knight",
        "Ranael",
        "Moss Giant",
        "Shopkeeper",
        "Shop Assistant",
        "Witch",
        "Black Knight",
        "Greldo",
        "Sir Amik Varze",
        "Guildmaster",
        "Valaine",
        "Drogo",
        "Imp",
        "Flynn",
        "Wyson the gardener",
        "Wizard Mizgog",
        "Prince Ali",
        "Hassan",
        "Osman",
        "Joe",
        "Leela",
        "Lady Keli",
        "Ned",
        "Aggie",
        "Prince Ali",
        "Jailguard",
        "Redbeard Frank",
        "Wydin",
        "shop assistant",
        "Brian",
        "squire",
        "Head chef",
        "Thurgo",
        "Ice Giant",
        "King Scorpion",
        "Pirate",
        "Sir Vyvin",
        "Monk of Zamorak",
        "Monk of Zamorak",
        "Wayne",
        "Barmaid",
        "Dwarven shopkeeper",
        "Doric",
        "Shopkeeper",
        "Shop Assistant",
        "Guide",
        "Hetty",
        "Betty",
        "Bartender",
        "General wartface",
        "General Bentnoze",
        "Goblin",
        "Goblin",
        "Herquin",
        "Rommik",
        "Grum",
        "Ice warrior",
        "Warrior",
        "Thrander",
        "Border Guard",
        "Border Guard",
        "Customs Officer",
        "Luthas",
        "Zambo",
        "Captain Tobias",
        "Gerrant",
        "Shopkeeper",
        "Shop Assistant",
        "Seaman Lorris",
        "Seaman Thresnor",
        "Tanner",
        "Dommik",
        "Abbot Langley",
        "Thordur",
        "Brother Jered",
        "Rat",
        "Ghost",
        "skeleton",
        "zombie",
        "Lesser Demon",
        "Melzar the mad",
        "Scavvo",
        "Greater Demon",
        "Shopkeeper",
        "Shop Assistant",
        "Oziach",
        "Bear",
        "Black Knight",
        "chaos Dwarf",
        "dwarf",
        "Wormbrain",
        "Klarense",
        "Ned",
        "skeleton",
        "Dragon",
        "Oracle",
        "Duke of Lumbridge",
        "Dark Warrior",
        "Druid",
        "Red Dragon",
        "Blue Dragon",
        "Baby Blue Dragon",
        "Kaqemeex",
        "Sanfew",
        "Suit of armour",
        "Adventurer",
        "Adventurer",
        "Adventurer",
        "Adventurer",
        "Leprechaun",
        "Monk of entrana",
        "Monk of entrana",
        "zombie",
        "Monk of entrana",
        "tree spirit",
        "cow",
        "Irksol",
        "Fairy Lunderwin",
        "Jakut",
        "Doorman",
        "Fairy Shopkeeper",
        "Fairy Shop Assistant",
        "Fairy banker",
        "Giles",
        "Miles",
        "Niles",
        "Gaius",
        "Fairy Ladder attendant",
        "Jatix",
        "Master Crafter",
        "Bandit",
        "Noterazzo",
        "Bandit",
        "Fat Tony",
        "Donny the lad",
        "Black Heather",
        "Speedy Keith",
        "White wolf sentry",
        "Boy",
        "Rat",
        "Nora T Hag",
        "Grey wolf",
        "shapeshifter",
        "shapeshifter",
        "shapeshifter",
        "shapeshifter",
        "White wolf",
        "Pack leader",
        "Harry",
        "Thug",
        "Firebird",
        "Achetties",
        "Ice queen",
        "Grubor",
        "Trobert",
        "Garv",
        "guard",
        "Grip",
        "Alfonse the waiter",
        "Charlie the cook",
        "Guard Dog",
        "Ice spider",
        "Pirate",
        "Jailer",
        "Lord Darquarius",
        "Seth",
        "Banker",
        "Helemos",
        "Chaos Druid",
        "Poison Scorpion",
        "Velrak the explorer",
        "Sir Lancelot",
        "Sir Gawain",
        "King Arthur",
        "Sir Mordred",
        "Renegade knight",
        "Davon",
        "Bartender",
        "Arhein",
        "Morgan le faye",
        "Candlemaker",
        "lady",
        "lady",
        "lady",
        "Beggar",
        "Merlin",
        "Thrantax",
        "Hickton",
        "Black Demon",
        "Black Dragon",
        "Poison Spider",
        "Monk of Zamorak",
        "Hellhound",
        "Animated axe",
        "Black Unicorn",
        "Frincos",
        "Otherworldly being",
        "Owen",
        "Thormac the sorceror",
        "Seer",
        "Kharid Scorpion",
        "Kharid Scorpion",
        "Kharid Scorpion",
        "Barbarian guard",
        "Bartender",
        "man",
        "gem trader",
        "Dimintheis",
        "chef",
        "Hobgoblin",
        "Ogre",
        "Boot the Dwarf",
        "Wizard",
        "Chronozon",
        "Captain Barnaby",
        "Customs Official",
        "Man",
        "farmer",
        "Warrior",
        "Guard",
        "Knight",
        "Paladin",
        "Hero",
        "Baker",
        "silk merchant",
        "Fur trader",
        "silver merchant",
        "spice merchant",
        "gem merchant",
        "Zenesha",
        "Kangai Mau",
        "Wizard Cromperty",
        "RPDT employee",
        "Horacio",
        "Aemad",
        "Kortan",
        "zoo keeper",
        "Make over mage",
        "Bartender",
        "chuck",
        "Rogue",
        "Shadow spider",
        "Fire Giant",
        "Grandpa Jack",
        "Sinister stranger",
        "Bonzo",
        "Forester",
        "Morris",
        "Brother Omad",
        "Thief",
        "Head Thief",
        "Big Dave",
        "Joshua",
        "Mountain Dwarf",
        "Mountain Dwarf",
        "Brother Cedric",
        "Necromancer",
        "zombie",
        "Lucien",
        "The Fire warrior of lesarkus",
        "guardian of Armadyl",
        "guardian of Armadyl",
        "Lucien",
        "winelda",
        "Brother Kojo",
        "Dungeon Rat",
        "Master fisher",
        "Orven",
        "Padik",
        "Shopkeeper",
        "Lady servil",
        "Guard",
        "Guard",
        "Guard",
        "Guard",
        "Jeremy Servil",
        "Justin Servil",
        "fightslave joe",
        "fightslave kelvin",
        "local",
        "Khazard Bartender",
        "General Khazard",
        "Khazard Ogre",
        "Guard",
        "Khazard Scorpion",
        "hengrad",
        "Bouncer",
        "Stankers",
        "Docky",
        "Shopkeeper",
        "Fairy queen",
        "Merlin",
        "Crone",
        "High priest of entrana",
        "elkoy",
        "remsai",
        "bolkoy",
        "local gnome",
        "bolren",
        "Black Knight titan",
        "kalron",
        "brother Galahad",
        "tracker 1",
        "tracker 2",
        "tracker 3",
        "Khazard troop",
        "commander montai",
        "gnome troop",
        "khazard warlord",
        "Sir Percival",
        "Fisher king",
        "maiden",
        "Fisherman",
        "King Percival",
        "unhappy peasant",
        "happy peasant",
        "ceril",
        "butler",
        "carnillean guard",
        "Tribesman",
        "henryeta",
        "philipe",
        "clivet",
        "cult member",
        "Lord hazeel",
        "alomone",
        "Khazard commander",
        "claus",
        "1st plague sheep",
        "2nd plague sheep",
        "3rd plague sheep",
        "4th plague sheep",
        "Farmer brumty",
        "Doctor orbon",
        "Councillor Halgrive",
        "Edmond",
        "Citizen",
        "Citizen",
        "Citizen",
        "Citizen",
        "Citizen",
        "Jethick",
        "Mourner",
        "Mourner",
        "Ted Rehnison",
        "Martha Rehnison",
        "Billy Rehnison",
        "Milli Rehnison",
        "Alrena",
        "Mourner",
        "Clerk",
        "Carla",
        "Bravek",
        "Caroline",
        "Holgart",
        "Holgart",
        "Holgart",
        "kent",
        "bailey",
        "kennith",
        "Platform Fisherman",
        "Platform Fisherman",
        "Platform Fisherman",
        "Elena",
        "jinno",
        "Watto",
        "Recruiter",
        "Head mourner",
        "Almera",
        "hudon",
        "hadley",
        "Rat",
        "Combat instructor",
        "golrie",
        "Guide",
        "King Black Dragon",
        "cooking instructor",
        "fishing instructor",
        "financial advisor",
        "gerald",
        "mining instructor",
        "Elena",
        "Omart",
        "Bank assistant",
        "Jerico",
        "Kilron",
        "Guidor's wife",
        "Quest advisor",
        "chemist",
        "Mourner",
        "Mourner",
        "Wilderness guide",
        "Magic Instructor",
        "Mourner",
        "Community instructor",
        "boatman",
        "skeleton mage",
        "controls guide",
        "nurse sarah",
        "Tailor",
        "Mourner",
        "Guard",
        "Chemist",
        "Chancy",
        "Hops",
        "DeVinci",
        "Guidor",
        "Chancy",
        "Hops",
        "DeVinci",
        "king Lathas",
        "Head wizard",
        "Magic store owner",
        "Wizard Frumscone",
        "target practice zombie",
        "Trufitus",
        "Colonel Radick",
        "Soldier",
        "Bartender",
        "Jungle Spider",
        "Jiminua",
        "Jogre",
        "Guard",
        "Ogre",
        "Guard",
        "Guard",
        "shop keeper",
        "Bartender",
        "Frenita",
        "Ogre chieftan",
        "rometti",
        "Rashiliyia",
        "Blurberry",
        "Heckel funch",
        "Aluft Gianne",
        "Hudo glenfad",
        "Irena",
        "Mosol",
        "Gnome banker",
        "King Narnode Shareen",
        "UndeadOne",
        "Drucas",
        "tourist",
        "King Narnode Shareen",
        "Hazelmere",
        "Glough",
        "Shar",
        "Shantay",
        "charlie",
        "Gnome guard",
        "Gnome pilot",
        "Mehman",
        "Ana",
        "Chaos Druid warrior",
        "Gnome pilot",
        "Shipyard worker",
        "Shipyard worker",
        "Shipyard worker",
        "Shipyard foreman",
        "Shipyard foreman",
        "Gnome guard",
        "Femi",
        "Femi",
        "Anita",
        "Glough",
        "Salarin the twisted",
        "Black Demon",
        "Gnome pilot",
        "Gnome pilot",
        "Gnome pilot",
        "Gnome pilot",
        "Sigbert the Adventurer",
        "Yanille Watchman",
        "Tower guard",
        "Gnome Trainer",
        "Gnome Trainer",
        "Gnome Trainer",
        "Gnome Trainer",
        "Blurberry barman",
        "Gnome waiter",
        "Gnome guard",
        "Gnome child",
        "Earth warrior",
        "Gnome child",
        "Gnome child",
        "Gulluck",
        "Gunnjorn",
        "Zadimus",
        "Brimstail",
        "Gnome child",
        "Gnome local",
        "Gnome local",
        "Moss Giant",
        "Gnome Baller",
        "Goalie",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Referee",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Gnome Baller",
        "Cheerleader",
        "Cheerleader",
        "Nazastarool Zombie",
        "Nazastarool Skeleton",
        "Nazastarool Ghost",
        "Fernahei",
        "Jungle Banker",
        "Cart Driver",
        "Cart Driver",
        "Obli",
        "Kaleb",
        "Yohnus",
        "Serevel",
        "Yanni",
        "Official",
        "Koftik",
        "Koftik",
        "Koftik",
        "Koftik",
        "Blessed Vermen",
        "Blessed Spider",
        "Paladin",
        "Paladin",
        "slave",
        "slave",
        "slave",
        "slave",
        "slave",
        "slave",
        "slave",
        "Kalrag",
        "Niloof",
        "Kardia the Witch",
        "Souless",
        "Othainian",
        "Doomion",
        "Holthion",
        "Klank",
        "Iban",
        "Koftik",
        "Goblin guard",
        "Observatory Professor",
        "Ugthanki",
        "Observatory assistant",
        "Souless",
        "Dungeon spider",
        "Kamen",
        "Iban disciple",
        "Koftik",
        "Goblin",
        "Chadwell",
        "Professor",
        "San Tojalon",
        "Ghost",
        "Spirit of Scorpius",
        "Scorpion",
        "Dark Mage",
        "Mercenary",
        "Mercenary Captain",
        "Mercenary",
        "Mining Slave",
        "Watchtower wizard",
        "Ogre Shaman",
        "Skavid",
        "Ogre guard",
        "Ogre guard",
        "Ogre guard",
        "Skavid",
        "Skavid",
        "Og",
        "Grew",
        "Toban",
        "Gorad",
        "Ogre guard",
        "Yanille Watchman",
        "Ogre merchant",
        "Ogre trader",
        "Ogre trader",
        "Ogre trader",
        "Mercenary",
        "City Guard",
        "Mercenary",
        "Lawgof",
        "Dwarf",
        "lollk",
        "Skavid",
        "Ogre guard",
        "Nulodion",
        "Dwarf",
        "Al Shabim",
        "Bedabin Nomad",
        "Captain Siad",
        "Bedabin Nomad Guard",
        "Ogre citizen",
        "Rock of ages",
        "Ogre",
        "Skavid",
        "Skavid",
        "Skavid",
        "Draft Mercenary Guard",
        "Mining Cart Driver",
        "kolodion",
        "kolodion",
        "Gertrude",
        "Shilop",
        "Rowdy Guard",
        "Shantay Pass Guard",
        "Rowdy Slave",
        "Shantay Pass Guard",
        "Assistant",
        "Desert Wolf",
        "Workman",
        "Examiner",
        "Student",
        "Student",
        "Guide",
        "Student",
        "Archaeological expert",
        "civillian",
        "civillian",
        "civillian",
        "civillian",
        "Murphy",
        "Murphy",
        "Sir Radimus Erkle",
        "Legends Guild Guard",
        "Escaping Mining Slave",
        "Workman",
        "Murphy",
        "Echned Zekin",
        "Donovan the Handyman",
        "Pierre the Dog Handler",
        "Hobbes the Butler",
        "Louisa The Cook",
        "Mary The Maid",
        "Stanford The Gardener",
        "Guard",
        "Guard Dog",
        "Guard",
        "Man",
        "Anna Sinclair",
        "Bob Sinclair",
        "Carol Sinclair",
        "David Sinclair",
        "Elizabeth Sinclair",
        "Frank Sinclair",
        "kolodion",
        "kolodion",
        "kolodion",
        "kolodion",
        "Irvig Senay",
        "Ranalph Devere",
        "Poison Salesman",
        "Gujuo",
        "Jungle Forester",
        "Ungadulu",
        "Ungadulu",
        "Death Wing",
        "Nezikchened",
        "Dwarf Cannon engineer",
        "Dwarf commander",
        "Viyeldi",
        "Nurmof",
        "Fatigue expert",
        "Karamja Wolf",
        "Jungle Savage",
        "Oomlie Bird",
        "Sidney Smith",
        "Siegfried Erkle",
        "Tea seller",
        "Wilough",
        "Philop",
        "Kanel",
        "chamber guardian",
        "Sir Radimus Erkle",
        "Pit Scorpion",
        "Shadow Warrior",
        "Fionella",
        "Battle mage",
        "Battle mage",
        "Battle mage",
        "Gundai",
        "Lundail"
    ]
}
