// Auto-generated from server GameObjectDef.xml

enum ObjectNames {
    static func name(for id: Int) -> String {
        guard id >= 0, id < names.count else { return "Object \(id)" }
        return names[id]
    }

    static let names: [String] = [
        "Tree",
        "Tree",
        "Well",
        "Table",
        "Treestump",
        "Ladder",
        "Ladder",
        "Chair",
        "logs",
        "Longtable",
        "Throne",
        "Range",
        "Gravestone",
        "Gravestone",
        "Bed",
        "Bed",
        "bar",
        "Chest",
        "Chest",
        "Altar",
        "Post",
        "Support",
        "barrel",
        "Bench",
        "Portrait",
        "candles",
        "fountain",
        "landscape",
        "Millstones",
        "Counter",
        "Stall",
        "Target",
        "PalmTree",
        "PalmTree",
        "Fern",
        "Cactus",
        "Bullrushes",
        "Flower",
        "Mushroom",
        "Coffin",
        "Coffin",
        "stairs",
        "stairs",
        "stairs",
        "stairs",
        "railing",
        "pillar",
        "Bookcase",
        "Sink",
        "Dummy",
        "anvil",
        "Torch",
        "hopper",
        "chute",
        "cart",
        "sacks",
        "cupboard",
        "Gate",
        "gate",
        "gate",
        "gate",
        "signpost",
        "signpost",
        "doors",
        "doors",
        "signpost",
        "signpost",
        "bookcase",
        "henge",
        "Dolmen",
        "Tree",
        "cupboard",
        "Wheat",
        "sign",
        "sails",
        "sign",
        "sign",
        "Drain",
        "manhole",
        "manhole",
        "pipe",
        "Chest",
        "Chest",
        "barrel",
        "cupboard",
        "cupboard",
        "fountain",
        "signpost",
        "Tree",
        "sign",
        "sign",
        "sign",
        "sign",
        "gate",
        "gate",
        "sign",
        "sign",
        "fire",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "web",
        "web",
        "furnace",
        "Cook's Range",
        "Machine",
        "Spinning wheel",
        "Lever",
        "Lever",
        "LeverA",
        "LeverB",
        "LeverC",
        "LeverD",
        "LeverE",
        "LeverF",
        "Ladder",
        "signpost",
        "signpost",
        "signpost",
        "Compost Heap",
        "Coffin",
        "Coffin",
        "gate",
        "gate",
        "sign",
        "cupboard",
        "cupboard",
        "doors",
        "torch",
        "Altar",
        "Shield",
        "Grill",
        "Cauldron",
        "Grill",
        "Mine Cart",
        "Buffers",
        "Track",
        "Track",
        "Track",
        "Hole",
        "ship",
        "ship",
        "ship",
        "Emergency escape ladder",
        "sign",
        "sign",
        "ship",
        "ship",
        "ship",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "hopper",
        "cupboard",
        "cupboard",
        "Rocks",
        "Doric's anvil",
        "pottery oven",
        "potter's wheel",
        "gate",
        "gate",
        "crate",
        "Banana tree",
        "Banana tree",
        "crate",
        "Chest",
        "Chest",
        "Flower",
        "sign",
        "sign",
        "Potato",
        "fish",
        "fish",
        "fish",
        "Rock",
        "Rock",
        "Rocks",
        "Ladder",
        "Ladder",
        "Monks Altar",
        "Ladder",
        "Coffin",
        "Coffin",
        "Smashed table",
        "Fungus",
        "Smashed chair",
        "Broken pillar",
        "Fallen tree",
        "Danger Sign",
        "Rock",
        "Rock",
        "Rocks",
        "Gravestone",
        "bone",
        "bone",
        "carcass",
        "animalskull",
        "Vine",
        "Vine",
        "Vine",
        "Chest",
        "Chest",
        "Ladder",
        "ship",
        "ship",
        "hole",
        "Ladder",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "hole",
        "ship",
        "ship",
        "Altar of Guthix",
        "The Cauldron of Thunder",
        "Tree",
        "ship",
        "ship",
        "ship",
        "ship",
        "ship",
        "ship",
        "Ladder",
        "Dramen Tree",
        "hopper",
        "Chest",
        "Chest",
        "Ladder",
        "sign",
        "sign",
        "gate",
        "gate",
        "gate",
        "Door mat",
        "gate",
        "Cauldron",
        "cupboard",
        "cupboard",
        "gate",
        "fish",
        "sign",
        "cupboard",
        "cupboard",
        "Chest",
        "Chest",
        "sign",
        "signpost",
        "Rockslide",
        "Ladder",
        "fish",
        "barrel",
        "table",
        "Fireplace",
        "Egg",
        "Eggs",
        "Stalagmites",
        "Stool",
        "Bench",
        "table",
        "table",
        "fountain of heros",
        "bush",
        "hedge",
        "flower",
        "plant",
        "Giant crystal",
        "sign",
        "sign",
        "crate",
        "crate",
        "ship",
        "ship",
        "beehive",
        "Ladder",
        "Altar",
        "sign",
        "signpost",
        "Archway",
        "Obelisk of water",
        "Obelisk of fire",
        "sand pit",
        "Obelisk of air",
        "Obelisk of earth",
        "gate",
        "Oak Tree",
        "Willow Tree",
        "Maple Tree",
        "Yew Tree",
        "Tree",
        "gate",
        "sign",
        "flax",
        "Large treestump",
        "Rocks",
        "Lever",
        "Lever",
        "Lever",
        "gate",
        "ship",
        "ship",
        "Bakers Stall",
        "Silk Stall",
        "Fur Stall",
        "Silver Stall",
        "Spices Stall",
        "gems Stall",
        "crate",
        "crate",
        "sign",
        "stairs",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "empty stall",
        "stairs",
        "hopper",
        "signpost",
        "sign",
        "gate",
        "gate",
        "Lever",
        "Lever",
        "pipe",
        "fish",
        "fish",
        "fish",
        "fish",
        "Vine",
        "gate",
        "gate",
        "gate",
        "stairs",
        "Broken Sleigh",
        "Lever",
        "clock pole blue",
        "clock pole red",
        "clock pole purple",
        "clock pole black",
        "wallclockface",
        "Lever Bracket",
        "Lever",
        "stairs",
        "stairs",
        "gate",
        "gate",
        "Lever",
        "Lever",
        "Foodtrough",
        "fish",
        "spearwall",
        "hornedskull",
        "Chest",
        "Chest",
        "guardscupboard",
        "guardscupboard",
        "Coal truck",
        "ship",
        "ship",
        "ship",
        "Tree",
        "Ballista",
        "largespear",
        "spirit tree",
        "young spirit Tree",
        "gate",
        "wall",
        "tree",
        "tree",
        "Fern",
        "Fern",
        "Fern",
        "Fern",
        "fly trap",
        "Fern",
        "Fern",
        "plant",
        "plant",
        "plant",
        "stone head",
        "dead Tree",
        "sacks",
        "khazard open Chest",
        "khazard shut Chest",
        "doorframe",
        "Sewer valve",
        "Sewer valve 2",
        "Sewer valve 3",
        "Sewer valve 4",
        "Sewer valve 5",
        "Cave entrance",
        "Log bridge",
        "Log bridge",
        "tree platform",
        "tree platform",
        "gate",
        "tree platform",
        "tree platform",
        "Log bridge",
        "Log bridge",
        "tree platform",
        "tree platform",
        "Tribal brew",
        "Pineapple tree",
        "Pineapple tree",
        "log raft",
        "log raft",
        "Tomb of hazeel",
        "range",
        "Bookcase",
        "Carnillean Chest",
        "Carnillean Chest",
        "crate",
        "Butlers cupboard",
        "Butlers cupboard",
        "gate",
        "gate",
        "Cattle furnace",
        "Ardounge wall",
        "Ardounge wall corner",
        "Dug up soil",
        "Pile of mud",
        "large Sewer pipe",
        "Ardounge wall gateway",
        "cupboard",
        "cupboard",
        "Fishing crane",
        "Rowboat",
        "Damaged Rowboat",
        "barrel",
        "gate",
        "Ladder",
        "Fishing crane",
        "Fishing crane",
        "Waterfall",
        "leaflessTree",
        "leaflessTree",
        "log raft",
        "doors",
        "Well",
        "Tomb of glarial",
        "Waterfall",
        "Waterfall",
        "Bookcase",
        "doors",
        "doors",
        "Stone stand",
        "Stone stand",
        "Stone stand",
        "Stone stand",
        "Stone stand",
        "Stone stand",
        "Glarial's Gravestone",
        "gate",
        "crate",
        "leaflessTree",
        "Statue of glarial",
        "Chalice of eternity",
        "Chalice of eternity",
        "doors",
        "Lever",
        "Lever",
        "log raft remains",
        "Tree",
        " Range",
        "crate",
        "fish",
        "Watch tower",
        "signpost",
        "Rocks",
        "doors",
        "Rope ladder",
        "cupboard",
        "cupboard",
        "Rope ladder",
        "Cooking pot",
        "Gallow",
        "gate",
        "crate",
        "cupboard",
        "cupboard",
        "gate",
        "cupboard",
        "cupboard",
        "sign",
        "grand tree",
        "gate",
        "gate",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Log bridge",
        "Watch tower",
        "Log bridge",
        "climbing rocks",
        "Ledge",
        "Ledge",
        "log",
        "log",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "PalmTree",
        "Scorched Earth",
        "Rocks",
        "sign",
        "fish",
        "Rocky Walkway",
        "Rocky Walkway",
        "Rocky Walkway",
        "Rocky Walkway",
        "fight Dummy",
        "gate",
        "Jungle Vine",
        "statue",
        "sign",
        "grand tree",
        "grand tree",
        "grand tree",
        "grand tree",
        "grand tree",
        "Hillside Entrance",
        "tree",
        "Log bridge",
        "Tree platform",
        "Tree platform",
        "Metalic Dungeon Gate",
        "Log bridge",
        "Log bridge",
        "Watch tower",
        "Watch tower",
        "Shallow water",
        "Doors",
        "grand tree",
        "Tree Ladder",
        "Tree Ladder",
        "blurberrys cocktail bar",
        "Gem Rocks",
        "Giannes place",
        "ropeswing",
        "net",
        "Frame",
        "Tree",
        "Tree",
        "Tree",
        "cart",
        "fence",
        "beam",
        "Sign",
        "Sign",
        "Sign",
        "Sign",
        "Sign",
        "Sign",
        "Sign",
        "Sign",
        "Sign",
        "Sign",
        "Root",
        "Root",
        "Metal Gate",
        "Metal Gate",
        "A farm cart",
        "Ledge",
        "Ledge",
        "Ladder",
        "cage",
        "glider",
        "cupboard",
        "cupboard",
        "stairs",
        "glider",
        "gate",
        "gate",
        "chaos altar",
        "Gnome stronghold gate",
        "ropeswing",
        "ropeswing",
        "stairs",
        "stairs",
        "Chest",
        "Chest",
        "Pile of rubble",
        "Stone stand",
        "Watch tower",
        "Pile of rubble",
        "Root",
        "Root",
        "Root",
        "Sign",
        "Hammock",
        "Goal",
        "stone tile",
        "Chest",
        "Chest",
        "Watch tower",
        "net",
        "Watch tower",
        "Watch tower",
        "ropeswing",
        "Bumpy Dirt",
        "pipe",
        "net",
        "pipe",
        "log",
        "pipe",
        "pipe",
        "Handholds",
        "Ladder",
        "gate",
        "stronghold spirit Tree",
        "Tree",
        "Tree",
        "Tree",
        "Spiked pit",
        "Spiked pit",
        "Cave",
        "stone pebble",
        "Pile of rubble",
        "Pile of rubble",
        "pipe",
        "pipe",
        "Stone",
        "Stone",
        "ropeswing",
        "log",
        "net",
        "Ledge",
        "Handholds",
        "log",
        "log",
        "Rotten Gallows",
        "Pile of rubble",
        "ropeswing",
        "ropeswing",
        "ocks",
        "Tree",
        "Well stacked rocks",
        "Tomb Dolmen",
        "Handholds",
        "Bridge Blockade",
        "Log Bridge",
        "Handholds",
        "Tree",
        "Tree",
        "Wet rocks",
        "Smashed table",
        "Crude Raft",
        "Daconia rock",
        "statue",
        "Stepping stones",
        "gate",
        "gate",
        "gate",
        "pipe",
        "ropeswing",
        "Stone",
        "Ledge",
        "Vine",
        "Rocks",
        "Wooden Gate",
        "Wooden Gate",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone platform",
        "fence",
        "Rocks",
        "Stone bridge",
        "Stone bridge",
        "Gate of Iban",
        "Wooden Door",
        "Tomb Dolmen",
        "Cave entrance",
        "Old bridge",
        "Old bridge",
        "Crumbled rock",
        "stalagmite",
        "stalagmite",
        "Rocks",
        "Ledge",
        "Lever",
        "stalactite",
        "stalactite",
        "stalactite",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Ledge",
        "Ledge",
        "Ledge",
        "Ledge",
        "Swamp",
        "Swamp",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Pile of mud",
        "Travel Cart",
        "Travel Cart",
        "Rocks",
        "stalactite",
        "Rocks",
        "Rocks",
        "Rocks",
        "sign",
        "Ladder",
        "Grill",
        "Spiked pit",
        "signpost",
        "Ship",
        "Ship",
        "Grill",
        "sacks",
        "Zamorakian Temple",
        "Grill",
        "Grill",
        "Grill",
        "Grill",
        "Grill",
        "Grill",
        "Grill",
        "Rocks",
        "Rocks",
        "Tomb Doors",
        "Swamp",
        "Rocks",
        "Rocks",
        "stalactite",
        "stalactite",
        "Spiked pit",
        "Lever",
        "Cage",
        "Cage",
        "Rocks",
        "Spear trap",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Ledge",
        "Furnace",
        "Well",
        "Passage",
        "Passage",
        "Passage",
        "stalagmite",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Passage",
        "snap trap",
        "Wooden planks",
        "Passage",
        "Passage",
        "Flames of zamorak",
        "Platform",
        "Rock",
        "Rock",
        "Rock",
        "Rock",
        "wall grill",
        "Ledge",
        "wall grill",
        "Dug up soil",
        "Dug up soil",
        "Pile of mud",
        "stalagmite",
        "Pile of mud",
        "Pile of mud",
        "Pile of mud",
        "Pile of mud",
        "Pile of mud",
        "Spiked pit",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Rocks",
        "Ledge",
        "Ledge",
        "Ledge",
        "Ledge",
        "Ledge",
        "Ledge",
        "Boulder",
        "crate",
        "Door",
        "Platform",
        "Cage remains",
        "Ledge",
        "Passage",
        "Passage",
        "Gate of Zamorak",
        "Rocks",
        "Bridge support",
        "Tomb of Iban",
        "Claws of Iban",
        "barrel",
        "Rock",
        "Rocks",
        "Rocks",
        "Swamp",
        "Chest",
        "Stone bridge",
        "cage",
        "cage",
        "Stone steps",
        "Pile of mud",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Stone bridge",
        "Chest",
        "Chest",
        "Pit of the Damned",
        "Open Door",
        "signpost",
        "Stone Gate",
        "Chest",
        "Zodiac",
        "Chest",
        "Ladder",
        "Stone steps",
        "Rock",
        "Rock",
        "Rock",
        "Telescope",
        "Gate",
        "sacks",
        "Ladder",
        "Chest",
        "Chest",
        "Bookcase",
        "Iron Gate",
        "Ladder",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "Rockslide",
        "Altar",
        "column",
        "Grave of Scorpius",
        "Bank Chest",
        "dwarf multicannon",
        "Disturbed sand",
        "Disturbed sand",
        "dwarf multicannon base",
        "dwarf multicannon stand",
        "dwarf multicannon barrels",
        "Cave",
        "Cave",
        "fence",
        "signpost",
        "Rocks",
        "Rocks",
        "Cave entrance",
        "Chest",
        "Chest",
        "Wooden Doors",
        "Pedestal",
        "bush",
        "bush",
        "Standard",
        "Mining Cave",
        "Mining Cave",
        "Rocks",
        "Lift",
        "Mining Barrel",
        "Hole",
        "Hole",
        "Cave",
        "Cave",
        "Cave",
        "Counter",
        "Track",
        "Cave",
        "Mine Cart",
        "Lift Platform",
        "Chest",
        "Chest",
        "Watch tower",
        "Ladder",
        "Cave entrance",
        "Pile of mud",
        "Cave",
        "Ladder",
        "crate",
        "crate",
        "Gate",
        "Gate",
        "bush",
        "bush",
        "bush",
        "bush",
        "multicannon",
        "Rocks",
        "Rocks",
        "Ladder",
        "Cave entrance",
        "Counter",
        "Chest",
        "Chest",
        "Chest",
        "Chest",
        "Bookcase",
        "Captains Chest",
        "Experimental Anvil",
        "Rocks",
        "Rocks",
        "Column",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Lever",
        "Lever",
        "Wall",
        "Ladder",
        "Wall",
        "Gate",
        "Gate",
        "Ladder",
        "shock",
        "Desk",
        "Cave",
        "Mining Cart",
        "Rock of Dalgroth",
        "entrance",
        "Dried Cactus",
        "climbing rocks",
        "Rocks",
        "lightning",
        "Crude Desk",
        "Heavy Metal Gate",
        "Counter",
        "Crude bed",
        "flames",
        "Carved Rock",
        "USE",
        "crate",
        "crate",
        "barrel",
        "Brick",
        "Brick",
        "Brick",
        "Brick",
        "Brick",
        "Brick",
        "Barrier",
        "buried skeleton",
        "Brick",
        "Brick",
        "Specimen tray",
        "winch",
        "crate",
        "crate",
        "Urn",
        "buried skeleton",
        "panning point",
        "Rocks",
        "signpost",
        "signpost",
        "signpost",
        "signpost",
        "signpost",
        "soil",
        "soil",
        "soil",
        "Gate",
        "ship",
        "barrel",
        "Leak",
        "bush",
        "bush",
        "cupboard",
        "sacks",
        "sacks",
        "Leak",
        "cupboard",
        "Wrought Mithril Gates",
        "Legends Hall Doors",
        "Camp bed",
        "barrel",
        "barrel",
        "Chest",
        "Chest",
        "Dense Jungle Tree",
        "Jungle tree stump",
        "signpost",
        "gate",
        "Bookcase",
        "Dense Jungle Tree",
        "Dense Jungle Tree",
        "Spray",
        "Spray",
        "winch",
        "Brick",
        "Rope",
        "Rope",
        "Dense Jungle Palm",
        "Dense Jungle Palm",
        "Trawler net",
        "Trawler net",
        "Brick",
        "Chest",
        "Chest",
        "Trawler catch",
        "Yommi Tree",
        "Grown Yommi Tree",
        "Chopped Yommi Tree",
        "Trimmed Yommi Tree",
        "Totem Pole",
        "Baby Yommi Tree",
        "Fertile earth",
        "Rock Hewn Stairs",
        "Hanging rope",
        "Rocks",
        "Boulder",
        "dwarf multicannon",
        "dwarf multicannon base",
        "dwarf multicannon stand",
        "dwarf multicannon barrels",
        "rock",
        "Rock Hewn Stairs",
        "Rock Hewn Stairs",
        "Rock Hewn Stairs",
        "Compost Heap",
        "beehive",
        "Drain",
        "web",
        "fountain",
        "Sinclair Crest",
        "barrel",
        "barrel",
        "barrel",
        "barrel",
        "barrel",
        "barrel",
        "Flour Barrel",
        "sacks",
        "gate",
        "Dead Yommi Tree",
        "clawspell",
        "Rocks",
        "crate",
        "Cavernous Opening",
        "Ancient Lava Furnace",
        "Spellcharge",
        "Rocks",
        "cupboard",
        "sacks",
        "Rock",
        "Saradomin stone",
        "Guthix stone",
        "Zamorak stone",
        "Magical pool",
        "Wooden Beam",
        "Rope down into darkness",
        "Cave entrance",
        "Cave entrance",
        "Ancient Wooden Doors",
        "Table",
        "Crude bed",
        "Tall Reeds",
        "Goblin foot prints",
        "Dark Metal Gate",
        "Magical pool",
        "Rope Up",
        "Half buried remains",
        "Blue Flag",
        "Red Flag",
        "Comfy bed",
        "Rotten Yommi Tree",
        "Rotten Yommi Tree",
        "Rotten Yommi Tree",
        "Rotten Totem Pole",
        "Leafy Palm Tree",
        "Grand Viziers Desk",
        "Strange Barrel",
        "ship",
        "ship",
        "ship",
        "digsite bed",
        "Tea stall",
        "Boulder",
        "Boulder",
        "Damaged Earth",
        "Ladder",
        "Ladder",
        "Vine",
        "Mysterious Ruins",
        "Air Altar",
        "Mysterious Ruins",
        "Mind Altar",
        "Mysterious Ruins",
        "Water Altar",
        "Mysterious Ruins",
        "Earth Altar",
        "Mysterious Ruins",
        "Fire Altar",
        "Mysterious Ruins",
        "Body Altar",
        "Mysterious Ruins",
        "Cosmic Altar",
        "Mysterious Ruins",
        "Chaos Altar",
        "Mysterious Ruins",
        "Nature Altar",
        "Mysterious Ruins",
        "Law Altar",
        "Mysterious Ruins",
        "Death Altar",
        "Mysterious Ruins",
        "Blood Altar",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Raw Rune stone",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "Portal",
        "pipe",
        "pipe",
        "Christmas Tree",
        "Decorated Tree",
        "Pine Tree",
        "Tunnel entrance",
        "Rowboat",
        "Lemon Tree",
        "Lime Tree",
        "Apple Tree",
        "Orange Tree",
        "Grapefruit Tree",
        "Banana Palm",
        "Coconut Palm",
        "Papaya Palm",
        "Pineapple Plant",
        "Exhausted Tree",
        "Exhausted Palm",
        "Exhausted Palm",
        "Exhausted Plant",
        "Redberry Bush",
        "Cadavaberry Bush",
        "Dwellberry Bush",
        "Jangerberry Bush",
        "Whiteberry Bush",
        "Depleted Bush",
        "Cabbage",
        "Red Cabbage",
        "White Pumpkin",
        "Potato Plant",
        "Onion Plant",
        "Garlic Plant",
        "Tomato Plant",
        "Corn Plant",
        "Damaged Ground",
        "Depleted tomato plant",
        "Depleted corn plant",
        "Snape Grass",
        "Herb",
        "Pumpkin",
        "Soil Mound",
        "Barrel of water",
        "Compost Bin",
        "Compost Bin",
        "Sea Weed",
        "Limpwurt Root",
        "Sugar Cane",
        "Mysterious Grape Vine",
        "Lava Forge",
        "anvil",
        "Rocks",
        "Stepping Stone",
        "Stepping Stone",
        "Stepping Stone",
        "Handholds",
        "Stepping Stone",
        "Stepping Stone",
        "Dragonfruit Tree",
        "Exhausted Tree",
        "Stepping Stone"
    ]
}
