[server]
log_level = "verbose"
secret_key = "2009scape_development"
write_logs = true
msip = "127.0.0.1"
preload_map = false
use_auth = false
persist_accounts = true
noauth_default_admin = true
daily_accounts_per_ip = 10
watchdog_enabled = false
connectivity_check_url = "https://google.com"
connectivity_timeout = 500

[database]
database_name = "global"
database_username = "root"
database_password = "2009scape_dev"
database_address = "db"
database_port = "3306"

[integrations]
grafana_logging = false
grafana_log_path = "@data/logs"
grafana_log_ttl_days = 7

[world]
name = "2009Scape"
name_ge = "2009Scape"
debug = true
dev = true
start_gui = false
daily_restart = false
world_id = "1"
country_id = "0"
members = true
activity = "2009Scape Web"
pvp = false
enable_default_clan = false
enable_bots = false
motw_identifier = "0"
motw_text = "Welcome to @name!"
new_player_location = "2524,5002,0"
home_location = "3222,3218,0"
autostock_ge = false
allow_token_purchase = false
skillcape_perks = false
increased_door_time = false
enable_botting = false
max_adv_bots = 0
enable_doubling_money_scammers = false
wild_pvp_enabled = false
jad_practice_enabled = false

[paths]
data_path = "data/"
cache_path = "data/cache/"
configs_path = "data/configs/"
save_path = "data/players/"
store_path = "data/eco/"
object_parser_path = "data/ObjectParser.xml"
logs_path = "data/logs/"
bot_data = "data/botdata/"
eco_data = "data/eco/"
rare_drop_table_path = "data/configs/shared_tables/RDT.xml"
cele_drop_table_path = "data/configs/shared_tables/CELEDT.xml"
uncommon_seed_drop_table_path = "data/configs/shared_tables/USDT.xml"
herb_drop_table_path = "data/configs/shared_tables/HDT.xml"
gem_drop_table_path = "data/configs/shared_tables/GDT.xml"
rare_seed_drop_table_path = "data/configs/shared_tables/RSDT.xml"
allotment_seed_drop_table_path = "data/configs/shared_tables/ASDT.xml"
